apiVersion: v1
kind: Secret
metadata:
  name: wasm-executor-tls
  namespace: wasm-executor
type: kubernetes.io/tls
data:
  tls.crt: Cg== # Placeholder for base64-encoded certificate
  tls.key: Cg== # Placeholder for base64-encoded private key