apiVersion: v1
kind: ConfigMap
metadata:
  name: wasm-executor-tls-certs
  namespace: wasm-executor
data:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    # Your base64-encoded public certificate (PEM format) goes here.
    # This is a placeholder.
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi...
    LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    # Your base64-encoded private key (PEM format) goes here.
    # This is a placeholder.
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tC...
    LS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
    -----END PRIVATE KEY-----